version: "3.4"
services:
  influxdb:
    image: influxdb
    ports:
     - "8086:8086"
    networks:
      - iot
      
  mongodb:
    image: mongo
    ports:
     - "27017:27017"
    networks:
      - iot

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - iot
  
  mqtt:
    build: 
      context: mqtt
      dockerfile: Dockerfile
    ports:
      - "1883:1883"
      - "15673:15672"
      - "5673:5672"
    networks:
      - iot

  postgres-keycloak-service:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    networks:
      - iot

  keycloak-service:
    build: 
      context: keycloak
      dockerfile: Dockerfile
    ports:
      - "9080:8080"
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres-keycloak-service
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
    networks:
      - iot

  nginx-service:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
    - "gtw-service:$DOCKERHOST"
    ports:
      - "80:80"
    networks:
      - iot



networks:
    iot:

volumes:
  postgres_data:
      driver: local
